### ISSUE TITLE
Tracking - Track events in GA

### ISSUE THREAD

**Issue by jeremypbeasley** [jeremypbeasley/rest_fundaday#21]
current list:

- taps on "learn more about the ERC"
- taps on "see the breakdown"
- taps on date-picker per user
- #'s a different dates were chosen
- taps on change month arrows.
- failed client side validation
- taps to submit
- taps to "understand the problem..."
- taps on "more about what we do."
- taps no "iwantrest.com" link at bottom
- taps on "i dont want my name..." checkbox

**Comment by thatericsmith** [comment]
- [x] taps on "learn more about the ERC"
- [x] taps on "see the breakdown"
- [x] taps on date-picker per user
- [x] #'s a different dates were chosen
- [x] taps on change month arrows.
- [x] failed client side validation
- [x] taps to submit
- [x] taps to "understand the problem..."
- [x] taps on "more about what we do."
- [x] taps no "iwantrest.com" link at bottom
- [x] taps on "i dont want my name..." checkbox

got these in 28ad7701233dd0a5ff9ef9ba590063d7daced1d5
